id = "dracula-theme"
name = "Dracula Theme"
version = "1.0.0"
schema_version = 1
authors = ["WangWindow <1598593280@qq.com>"]
description = "Dracula theme for Zed"
repository = "https://github.com/WangWindows/dracula-theme-zed"
