id = "dracula-flat"
name = "Dracula Flat"
version = "1.0.1"
schema_version = 1
authors = ["WangWindow <1598593280@qq.com>"]
description = "Dracula theme (flat version) for Zed"
repository = "https://github.com/WangWindows/dracula-theme-zed"
